@startuml
hide empty description

state GlobalWorkflow {
  [*] -d--> Parameterization
  Parameterization -down--> Routinization
  Routinization -down--> Normalization
  Normalization -down--> [*]: TODO
}

@enduml